project_id = "hokkweglaumudsmphmbv"

[functions.verify-address]
verify_jwt = true

[functions.send-postcard]
verify_jwt = true

[functions.lob-webhook]
verify_jwt = false

[functions.handle-actblue-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false