project_id = "eticfuarcjfjvyytczpm"

[verify-address]
verify_jwt = true

[send-postcard]
verify_jwt = true

[handle-actblue-webhook]
verify_jwt = false

[retry-postcard]
verify_jwt = true

[process-address-queue]
verify_jwt = true

[process-postcard-queue]
verify_jwt = true