// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hokkweglaumudsmphmbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhva2t3ZWdsYXVtdWRzbXBobWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTUzMDgsImV4cCI6MjA0OTk3MTMwOH0.RnV9oEbUYcTtw--k4G8B2Z4hCmBrpXJwOG_iynBlwas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);